abstract: Total Failure
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
build_requires: 
  Test::Base: 0.50
distribution_type: module
generated_by: Module::Install version 0.54
license: perl
name: orz
no_index: 
  directory: 
    - inc
    - t
requires: 
  Module::Compile: 0.12
  perl: 5.6.1
version: 0.11
